// src/lib/convex.ts - Updated for Desktop Auth


/**
 * This file is used to interact with the Convex database.
 * It is used to get the stored token, run queries, and run mutations.
 * It is also used to run actions.
 * It is also used to set the auth token on the Convex client.
 * It is also used to clear the auth token on the Convex client.
 * It is also used to update the auth token on the Convex client.
 * 
 * 
 * DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING.
 */
import { ConvexReactClient } from "convex/react";
import type { FunctionReference, FunctionReturnType } from "convex/server";
import { invoke } from '@tauri-apps/api/core';

// Create a shared Convex client instance
const client = new ConvexReactClient(import.meta.env.VITE_CONVEX_URL);

// Storage key for auth token
const STORAGE_KEY = 'dealer_auth_token';

// Helper to get stored token
export async function getStoredToken(): Promise<string | null> {
  try {
    const token = await invoke<string | null>('retrieve_secure', { key: STORAGE_KEY });
    return token;
  } catch (error) {
    console.error('Failed to retrieve token:', error);
    return null;
  }
}

// Helper to run Convex queries with auto-injected auth token
export async function convexQuery<Query extends FunctionReference<"query">>(
  query: Query,
  args: Query["_args"]
): Promise<FunctionReturnType<Query>> {
  // Desktop auth: token passed explicitly in args, don't auto-inject
  return client.query(query, args);  // ✅ Just pass args as-is
}

// Helper to run Convex mutations with auto-injected auth token
export async function convexMutation<Mutation extends FunctionReference<"mutation">>(
  mutation: Mutation,
  args: Mutation["_args"]
): Promise<FunctionReturnType<Mutation>> {
  // Desktop auth: token passed explicitly in args, don't auto-inject
  return client.mutation(mutation, args);  // ✅ Just pass args as-is
}

// Helper to run Convex actions
export async function convexAction<Action extends FunctionReference<"action">>(
  action: Action,
  args: Action["_args"]
): Promise<FunctionReturnType<Action>> {
  return client.action(action, args);
}

// Set auth token when available (kept for backwards compatibility)
export function setConvexAuth(_token: string | null) {
  // Token is now passed in each query/mutation instead of set globally
  // This function is kept for backwards compatibility
  console.log('🔐 Convex auth token updated');
}

export { client as convexClient };