// src/lib/convex.ts - Updated for Desktop Auth


/**
 * This file is used to interact with the Convex database.
 * It is used to get the stored token, run queries, and run mutations.
 * It is also used to run actions.
 * It is also used to set the auth token on the Convex client.
 * It is also used to clear the auth token on the Convex client.
 * It is also used to update the auth token on the Convex client.
 * 
 * 
 * DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING.
 */
import { ConvexReactClient } from "convex/react";
import type { FunctionReference, FunctionReturnType } from "convex/server";
import { invoke } from '@tauri-apps/api/core';

// Create a shared Convex client instance
const client = new ConvexReactClient(import.meta.env.VITE_CONVEX_URL);

// Helper to get stored token
// SECURITY: Uses specific dealership auth token command instead of generic secure storage
export async function getStoredToken(): Promise<string | null> {
  try {
    const token = await invoke<string | null>('get_dealership_auth_token');
    return token;
  } catch (error) {
    console.error('Failed to retrieve token:', error);
    return null;
  }
}

// Helper to run Convex queries with auto-injected auth token
// Accepts function references with or without _componentPath (handles api.api.* references)
export async function convexQuery<Query extends FunctionReference<"query">>(
  query: any,
  args: Query["_args"]
): Promise<FunctionReturnType<Query>> {
  // Desktop auth: token passed explicitly in args, don't auto-inject
  // Type assertion handles missing _componentPath in api.api.* references
  return client.query(query as unknown as Query, args);
}

// Helper to run Convex mutations with auto-injected auth token
// Accepts function references with or without _componentPath (handles api.api.* references)
export async function convexMutation<Mutation extends FunctionReference<"mutation">>(
  mutation: any,
  args: Mutation["_args"]
): Promise<FunctionReturnType<Mutation>> {
  // Desktop auth: token passed explicitly in args, don't auto-inject
  // Type assertion handles missing _componentPath in api.api.* references
  return client.mutation(mutation as unknown as Mutation, args);
}

// Helper to run Convex actions
// Accepts function references with or without _componentPath (handles api.api.* references)
export async function convexAction<Action extends FunctionReference<"action">>(
  action: any,
  args: Action["_args"]
): Promise<FunctionReturnType<Action>> {
  // Type assertion handles missing _componentPath in api.api.* references
  return client.action(action as unknown as Action, args);
}

// Set auth token when available (kept for backwards compatibility)
export function setConvexAuth(_token: string | null) {
  // Token is now passed in each query/mutation instead of set globally
  // This function is kept for backwards compatibility
  console.log('🔐 Convex auth token updated');
}

export { client as convexClient };