/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsNewRouteImport } from './routes/whats-new'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as StandaloneLoginRouteImport } from './routes/standalone-login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LicenseActivationRouteImport } from './routes/license-activation'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DealershipRouteImport } from './routes/dealership'
import { Route as AccountSetupRouteImport } from './routes/account-setup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DealsIndexRouteImport } from './routes/deals/index'
import { Route as DealsNewIndexRouteImport } from './routes/deals/new/index'
import { Route as DealsDealsIdIndexRouteImport } from './routes/deals/$dealsId/index'
import { Route as DealsDealsIdDocumentsIndexRouteImport } from './routes/deals/$dealsId/documents/index'
import { Route as DealsDealsIdDocumentsDocumentsRouteImport } from './routes/deals/$dealsId/documents/$documents'

const WhatsNewRoute = WhatsNewRouteImport.update({
  id: '/whats-new',
  path: '/whats-new',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const StandaloneLoginRoute = StandaloneLoginRouteImport.update({
  id: '/standalone-login',
  path: '/standalone-login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseActivationRoute = LicenseActivationRouteImport.update({
  id: '/license-activation',
  path: '/license-activation',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DealershipRoute = DealershipRouteImport.update({
  id: '/dealership',
  path: '/dealership',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSetupRoute = AccountSetupRouteImport.update({
  id: '/account-setup',
  path: '/account-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsNewIndexRoute = DealsNewIndexRouteImport.update({
  id: '/deals/new/',
  path: '/deals/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsDealsIdIndexRoute = DealsDealsIdIndexRouteImport.update({
  id: '/deals/$dealsId/',
  path: '/deals/$dealsId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsDealsIdDocumentsIndexRoute =
  DealsDealsIdDocumentsIndexRouteImport.update({
    id: '/deals/$dealsId/documents/',
    path: '/deals/$dealsId/documents/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DealsDealsIdDocumentsDocumentsRoute =
  DealsDealsIdDocumentsDocumentsRouteImport.update({
    id: '/deals/$dealsId/documents/$documents',
    path: '/deals/$dealsId/documents/$documents',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-setup': typeof AccountSetupRoute
  '/dealership': typeof DealershipRoute
  '/help': typeof HelpRoute
  '/license-activation': typeof LicenseActivationRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/standalone-login': typeof StandaloneLoginRoute
  '/subscribe': typeof SubscribeRoute
  '/subscription': typeof SubscriptionRoute
  '/whats-new': typeof WhatsNewRoute
  '/deals': typeof DealsIndexRoute
  '/deals/$dealsId': typeof DealsDealsIdIndexRoute
  '/deals/new': typeof DealsNewIndexRoute
  '/deals/$dealsId/documents/$documents': typeof DealsDealsIdDocumentsDocumentsRoute
  '/deals/$dealsId/documents': typeof DealsDealsIdDocumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-setup': typeof AccountSetupRoute
  '/dealership': typeof DealershipRoute
  '/help': typeof HelpRoute
  '/license-activation': typeof LicenseActivationRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/standalone-login': typeof StandaloneLoginRoute
  '/subscribe': typeof SubscribeRoute
  '/subscription': typeof SubscriptionRoute
  '/whats-new': typeof WhatsNewRoute
  '/deals': typeof DealsIndexRoute
  '/deals/$dealsId': typeof DealsDealsIdIndexRoute
  '/deals/new': typeof DealsNewIndexRoute
  '/deals/$dealsId/documents/$documents': typeof DealsDealsIdDocumentsDocumentsRoute
  '/deals/$dealsId/documents': typeof DealsDealsIdDocumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-setup': typeof AccountSetupRoute
  '/dealership': typeof DealershipRoute
  '/help': typeof HelpRoute
  '/license-activation': typeof LicenseActivationRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/standalone-login': typeof StandaloneLoginRoute
  '/subscribe': typeof SubscribeRoute
  '/subscription': typeof SubscriptionRoute
  '/whats-new': typeof WhatsNewRoute
  '/deals/': typeof DealsIndexRoute
  '/deals/$dealsId/': typeof DealsDealsIdIndexRoute
  '/deals/new/': typeof DealsNewIndexRoute
  '/deals/$dealsId/documents/$documents': typeof DealsDealsIdDocumentsDocumentsRoute
  '/deals/$dealsId/documents/': typeof DealsDealsIdDocumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-setup'
    | '/dealership'
    | '/help'
    | '/license-activation'
    | '/login'
    | '/profile'
    | '/search'
    | '/settings'
    | '/standalone-login'
    | '/subscribe'
    | '/subscription'
    | '/whats-new'
    | '/deals'
    | '/deals/$dealsId'
    | '/deals/new'
    | '/deals/$dealsId/documents/$documents'
    | '/deals/$dealsId/documents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-setup'
    | '/dealership'
    | '/help'
    | '/license-activation'
    | '/login'
    | '/profile'
    | '/search'
    | '/settings'
    | '/standalone-login'
    | '/subscribe'
    | '/subscription'
    | '/whats-new'
    | '/deals'
    | '/deals/$dealsId'
    | '/deals/new'
    | '/deals/$dealsId/documents/$documents'
    | '/deals/$dealsId/documents'
  id:
    | '__root__'
    | '/'
    | '/account-setup'
    | '/dealership'
    | '/help'
    | '/license-activation'
    | '/login'
    | '/profile'
    | '/search'
    | '/settings'
    | '/standalone-login'
    | '/subscribe'
    | '/subscription'
    | '/whats-new'
    | '/deals/'
    | '/deals/$dealsId/'
    | '/deals/new/'
    | '/deals/$dealsId/documents/$documents'
    | '/deals/$dealsId/documents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountSetupRoute: typeof AccountSetupRoute
  DealershipRoute: typeof DealershipRoute
  HelpRoute: typeof HelpRoute
  LicenseActivationRoute: typeof LicenseActivationRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StandaloneLoginRoute: typeof StandaloneLoginRoute
  SubscribeRoute: typeof SubscribeRoute
  SubscriptionRoute: typeof SubscriptionRoute
  WhatsNewRoute: typeof WhatsNewRoute
  DealsIndexRoute: typeof DealsIndexRoute
  DealsDealsIdIndexRoute: typeof DealsDealsIdIndexRoute
  DealsNewIndexRoute: typeof DealsNewIndexRoute
  DealsDealsIdDocumentsDocumentsRoute: typeof DealsDealsIdDocumentsDocumentsRoute
  DealsDealsIdDocumentsIndexRoute: typeof DealsDealsIdDocumentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whats-new': {
      id: '/whats-new'
      path: '/whats-new'
      fullPath: '/whats-new'
      preLoaderRoute: typeof WhatsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standalone-login': {
      id: '/standalone-login'
      path: '/standalone-login'
      fullPath: '/standalone-login'
      preLoaderRoute: typeof StandaloneLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license-activation': {
      id: '/license-activation'
      path: '/license-activation'
      fullPath: '/license-activation'
      preLoaderRoute: typeof LicenseActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dealership': {
      id: '/dealership'
      path: '/dealership'
      fullPath: '/dealership'
      preLoaderRoute: typeof DealershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-setup': {
      id: '/account-setup'
      path: '/account-setup'
      fullPath: '/account-setup'
      preLoaderRoute: typeof AccountSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/': {
      id: '/deals/'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/new/': {
      id: '/deals/new/'
      path: '/deals/new'
      fullPath: '/deals/new'
      preLoaderRoute: typeof DealsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$dealsId/': {
      id: '/deals/$dealsId/'
      path: '/deals/$dealsId'
      fullPath: '/deals/$dealsId'
      preLoaderRoute: typeof DealsDealsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$dealsId/documents/': {
      id: '/deals/$dealsId/documents/'
      path: '/deals/$dealsId/documents'
      fullPath: '/deals/$dealsId/documents'
      preLoaderRoute: typeof DealsDealsIdDocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$dealsId/documents/$documents': {
      id: '/deals/$dealsId/documents/$documents'
      path: '/deals/$dealsId/documents/$documents'
      fullPath: '/deals/$dealsId/documents/$documents'
      preLoaderRoute: typeof DealsDealsIdDocumentsDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountSetupRoute: AccountSetupRoute,
  DealershipRoute: DealershipRoute,
  HelpRoute: HelpRoute,
  LicenseActivationRoute: LicenseActivationRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StandaloneLoginRoute: StandaloneLoginRoute,
  SubscribeRoute: SubscribeRoute,
  SubscriptionRoute: SubscriptionRoute,
  WhatsNewRoute: WhatsNewRoute,
  DealsIndexRoute: DealsIndexRoute,
  DealsDealsIdIndexRoute: DealsDealsIdIndexRoute,
  DealsNewIndexRoute: DealsNewIndexRoute,
  DealsDealsIdDocumentsDocumentsRoute: DealsDealsIdDocumentsDocumentsRoute,
  DealsDealsIdDocumentsIndexRoute: DealsDealsIdDocumentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
