/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DealsIndexRouteImport } from './routes/deals/index'
import { Route as DealsNewIndexRouteImport } from './routes/deals/new/index'
import { Route as DealsDealsIdIndexRouteImport } from './routes/deals/$dealsId/index'
import { Route as DealsDealsIdDocumentsRouteImport } from './routes/deals/$dealsId/documents'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsNewIndexRoute = DealsNewIndexRouteImport.update({
  id: '/deals/new/',
  path: '/deals/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsDealsIdIndexRoute = DealsDealsIdIndexRouteImport.update({
  id: '/deals/$dealsId/',
  path: '/deals/$dealsId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsDealsIdDocumentsRoute = DealsDealsIdDocumentsRouteImport.update({
  id: '/deals/$dealsId/documents',
  path: '/deals/$dealsId/documents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/deals': typeof DealsIndexRoute
  '/deals/$dealsId/documents': typeof DealsDealsIdDocumentsRoute
  '/deals/$dealsId': typeof DealsDealsIdIndexRoute
  '/deals/new': typeof DealsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/deals': typeof DealsIndexRoute
  '/deals/$dealsId/documents': typeof DealsDealsIdDocumentsRoute
  '/deals/$dealsId': typeof DealsDealsIdIndexRoute
  '/deals/new': typeof DealsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/deals/': typeof DealsIndexRoute
  '/deals/$dealsId/documents': typeof DealsDealsIdDocumentsRoute
  '/deals/$dealsId/': typeof DealsDealsIdIndexRoute
  '/deals/new/': typeof DealsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/deals'
    | '/deals/$dealsId/documents'
    | '/deals/$dealsId'
    | '/deals/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/deals'
    | '/deals/$dealsId/documents'
    | '/deals/$dealsId'
    | '/deals/new'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/deals/'
    | '/deals/$dealsId/documents'
    | '/deals/$dealsId/'
    | '/deals/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  DealsIndexRoute: typeof DealsIndexRoute
  DealsDealsIdDocumentsRoute: typeof DealsDealsIdDocumentsRoute
  DealsDealsIdIndexRoute: typeof DealsDealsIdIndexRoute
  DealsNewIndexRoute: typeof DealsNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/': {
      id: '/deals/'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/new/': {
      id: '/deals/new/'
      path: '/deals/new'
      fullPath: '/deals/new'
      preLoaderRoute: typeof DealsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$dealsId/': {
      id: '/deals/$dealsId/'
      path: '/deals/$dealsId'
      fullPath: '/deals/$dealsId'
      preLoaderRoute: typeof DealsDealsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$dealsId/documents': {
      id: '/deals/$dealsId/documents'
      path: '/deals/$dealsId/documents'
      fullPath: '/deals/$dealsId/documents'
      preLoaderRoute: typeof DealsDealsIdDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  DealsIndexRoute: DealsIndexRoute,
  DealsDealsIdDocumentsRoute: DealsDealsIdDocumentsRoute,
  DealsDealsIdIndexRoute: DealsDealsIdIndexRoute,
  DealsNewIndexRoute: DealsNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
